spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${jdbc.database};MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: eap
    password: eap
  security:
    oauth2:
      authorizationserver:
        issuer: http://127.0.0.1:8080
  sql:
    init:
      schema-locations: classpath:init-h2.sql
      mode: always


jdbc:
  database: eap
